// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour.Data;

namespace Tour.Migrations
{
    [DbContext(typeof(TourContext))]
    [Migration("20201124045929_Ratings")]
    partial class Ratings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tour.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 1,
                            Name = "Milano"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 1,
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/417192/pexels-photo-417192.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 1,
                            Name = "Miami"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1525612/pexels-photo-1525612.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 1,
                            Name = "New Delh"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/936722/pexels-photo-936722.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 1,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1525612/pexels-photo-1525612.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "London"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/3065260/pexels-photo-3065260.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1036657/pexels-photo-1036657.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1334605/pexels-photo-1334605.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=300",
                            LocationId = 2,
                            Name = "Ny City"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1697358/pexels-photo-1697358.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2022, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/58603/pexels-photo-58603.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/2116721/pexels-photo-2116721.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1738997/pexels-photo-1738997.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/374811/pexels-photo-374811.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/302769/pexels-photo-302769.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Zurich"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/416998/pexels-photo-416998.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1485894/pexels-photo-1485894.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 1,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/3065260/pexels-photo-3065260.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Osaka"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/416998/pexels-photo-416998.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 3,
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "WA,DC"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/681335/pexels-photo-681335.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Bogota"
                        });
                });

            modelBuilder.Entity("Tour.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Continent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Continent = "Africa and Asia",
                            Place = "City Parks,  Historical Places and Technology Invantions Areas"
                        },
                        new
                        {
                            LocationId = 2,
                            Continent = "America and Asia Africa",
                            Place = "City Parks,  Historical Places and Technology Invantions Areas"
                        },
                        new
                        {
                            LocationId = 3,
                            Continent = "America, Africa and Asia",
                            Place = "City Parks,  Historical Places and Technology Invantions Areas"
                        },
                        new
                        {
                            LocationId = 4,
                            Continent = "America and Asia",
                            Place = "City Parks,  Historical Places and Technology Invantions Areas"
                        });
                });

            modelBuilder.Entity("Tour.Models.Upcoming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Upcomings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/3065260/pexels-photo-3065260.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "Osaka"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/416998/pexels-photo-416998.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 3,
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id feugiat quam. Etiam eros leo, faucibus iaculis tempor ac, faucibus ut velit. Sed nunc elit, efficitur tristique tristique eu, vestibulum et purus. Nullam at dolor ac elit elementum interdum. Donec eget enim vel orci convallis tincidunt at eget odio. Aliquam congue vel tortor vitae gravida. Vestibulum vulputate nisl vel semper posuere. Nulla elementum scelerisque odio, eu elementum nisi commodo sed. Donec aliquet venenatis faucibus. Donec lacinia ante dui, luctus viverra orci volutpat porttitor. Nullam non nunc elit. Proin gravida vulputate massa, eget posuere mi. Integer et fermentum velit. Quisque laoreet dignissim arcu, non malesuada odio dictum vel. Nam mollis ultricies massa eget blandit",
                            EventDate = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            LocationId = 2,
                            Name = "WA,DC"
                        });
                });

            modelBuilder.Entity("Tour.Models.City", b =>
                {
                    b.HasOne("Tour.Models.Location", "Location")
                        .WithMany("Cities")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Tour.Models.Upcoming", b =>
                {
                    b.HasOne("Tour.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
